[network]
my_id = 2
bind_addr = "0.0.0.0:10002"
timeout = "30min"
connect_timeout = "60s"

[[network.parties]]
id = 0
dns_name = "127.0.0.1:10000"

[[network.parties]]
id = 1
dns_name = "127.0.0.1:10001"

[[network.parties]]
id = 2
dns_name = "127.0.0.1:10002"
