[package]
name = "circom-mpc-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
circom-mpc-program = { path = "../circom-mpc-program/" }
eyre.workspace = true
mpc-core.workspace = true
mpc-net.workspace = true
num-bigint.workspace = true
num-traits.workspace = true

[dev-dependencies]
mpc-net = { workspace = true, features = ["local"] }
rand.workspace = true

[features]
default = []
local = ["mpc-net/local"]
quic = ["mpc-net/quic"]
tcp = ["mpc-net/tcp"]
tcp-session = ["mpc-net/tcp-session"]
tcp-session-blocking = ["mpc-net/tcp-session-blocking"]
tls = ["mpc-net/tls"]
