[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
ark-bn254 = "0.5"
ark-ff = "0.5"
ark-serialize = { version = "0.5", features = ["derive", "std"] }
circom-compiler = { package = "compiler", git = "https://github.com/TaceoLabs/circom", rev = "1cc17fb", version = "2.1.9" }
circom-constraint_generation = { package = "constraint_generation", git = "https://github.com/TaceoLabs/circom", rev = "1cc17fb", version = "2.1.9" }
circom-parser = { package = "parser", git = "https://github.com/TaceoLabs/circom", rev = "1cc17fb", version = "2.1.9" }
circom-program_structure = { package = "program_structure", git = "https://github.com/TaceoLabs/circom", rev = "1cc17fb", version = "2.1.9" }
circom-type_analysis = { package = "type_analysis", git = "https://github.com/TaceoLabs/circom", rev = "1cc17fb", version = "2.1.9" }
circom-types = { package = "taceo-circom-types", version = "0.2" }
clap = { version = "4.5", features = ["derive"] }
co-circom-types = { git = "https://github.com/TaceoLabs/co-snarks", rev = "cb6d363", version = "0.6.0" }
co-groth16 = { git = "https://github.com/TaceoLabs/co-snarks", rev = "cb6d363", version = "0.10.0" }
criterion = "0.5"
eyre = "0.6.12"
mpc-core = { git = "https://github.com/TaceoLabs/co-snarks", rev = "cb6d363", version = "0.10.0" }
mpc-net = { git = "https://github.com/TaceoLabs/co-snarks", rev = "cb6d363", version = "0.5.0" }
num-bigint = { version = "0.4.6" }
num-traits = { version = "0.2.18", default-features = false }
rand = { version = "0.8.5" }
rustc-hash = "2"
rustls = { version = "0.23" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0"
toml = { version = "0.8" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
allow_attributes_without_reason = "deny"
assertions_on_result_states = "deny"
dbg_macro = "deny"
decimal_literal_representation = "deny"
iter_over_hash_type = "deny"
let_underscore_must_use = "deny"
missing_assert_message = "deny"
pedantic = { level = "deny", priority = -1 }
print_stderr = "deny"
print_stdout = "deny"
undocumented_unsafe_blocks = "deny"
unnecessary_safety_comment = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
missing_docs = "deny"
