[package]
name = "circom-mpc-compiler"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "circom-mpc-compile"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
circom-compiler.workspace = true
circom-constraint_generation.workspace = true
circom-mpc-program = { path = "../circom-mpc-program" }
circom-parser.workspace = true
circom-program_structure.workspace = true
circom-type_analysis.workspace = true
clap = { workspace = true, optional = true }
eyre.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
rustc-hash.workspace = true
serde = { workspace = true }
toml = { workspace = true, optional = true }
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }

[features]
cli = ["dep:clap", "dep:toml", "dep:tracing-subscriber"]

[lints]
workspace = true
