[package]
name = "circom-mpc-compiler-tests"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "merces-net"
path = "src/bin/merces-net.rs"
required-features = ["tls"]

[[example]]
name = "merces"
required-features = ["local"]

[[test]]
name = "merces"
required-features = ["local"]

[[test]]
name = "proving"
required-features = ["local"]

[[test]]
name = "rep3_vm"
required-features = ["local"]

[[bench]]
harness = false
name = "compile"

[[bench]]
harness = false
name = "merces"
required-features = ["local"]

[[bench]]
harness = false
name = "witness_extension"
required-features = ["local"]

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
circom-mpc-compiler = { path = "../circom-mpc-compiler" }
circom-mpc-program = { path = "../circom-mpc-program" }
circom-mpc-vm = { path = "../circom-mpc-vm", default-features = false }
clap = { workspace = true, optional = true }
eyre.workspace = true
mpc-core.workspace = true
mpc-net.workspace = true
num-bigint.workspace = true
rand.workspace = true
rustls = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json.workspace = true
toml = { workspace = true, optional = true }
tracing-subscriber.workspace = true

[dev-dependencies]
ark-serialize.workspace = true
circom-types.workspace = true
co-circom-types.workspace = true
co-groth16 = { workspace = true, features = ["verifier"] }
criterion.workspace = true

[features]
default = ["local"]
local = ["circom-mpc-vm/local", "mpc-net/local"]
quic = ["circom-mpc-vm/quic", "mpc-net/quic"]
tcp = ["circom-mpc-vm/tcp", "mpc-net/tcp"]
tcp-session = ["circom-mpc-vm/tcp-session", "mpc-net/tcp-session"]
tcp-session-blocking = ["circom-mpc-vm/tcp-session-blocking", "mpc-net/tcp-session-blocking"]
tls = [
  "circom-mpc-vm/tls",
  "dep:clap",
  "dep:rustls",
  "dep:serde",
  "dep:toml",
  "mpc-net/tls",
]
